### ISSUE TITLE
Incorrect workspace path in installing scripts

### ISSUE THREAD

**Issue by mikobski** [mikobski/Critbot#14]
Moim zdaniem te skrypty do instalacji rosa, symulacji itp. są popsute. Tworzą one chociażby folder catkin_ws który moim zdaniem jest niepotrzebny. Wszystkie budowane pliki powinny pojawić się w folderze naszego repo lokalnei na dysku. Natomiast żeby git ich nie zaciągnął do repo, trzeba będzie dodać je do .gitignore.

**Comment by CebulowyNinja** [comment]
Zgadzam się, że catkin_ws powinien być w repo, ponieważ będzie tam nasz kod źródłowy. Reszta (Gazebo, Ardupilot itp.) nie mam pojęcia.
Co do .gitignore to można dodać, ale pewnie trochę w ciemno będzie na tym etapie.
